name: "CI detector"

on:
  workflow_call:
    outputs:
      php-supported-versions:
        value: ${{ jobs.detect-php-versions.outputs.versions }}
      php-lowest-version:
        value: ${{ jobs.detect-php-versions.outputs.lowest-version }}
      php-highest-version:
        value: ${{ jobs.detect-php-versions.outputs.highest-version }}
      phpunit:
        value: ${{ jobs.detect-tools.outputs.phpunit }}
      infection:
        value: ${{ jobs.detect-tools.outputs.infection }}
      php-cs-fixer:
        value: ${{ jobs.detect-tools.outputs.php-cs-fixer }}
      psalm:
        value: ${{ jobs.detect-tools.outputs.psalm }}

jobs:
  detect-php-versions:
    name: "PHP versions from composer.json"
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.supported-versions-matrix.outputs.version }}
      lowest-version: ${{ steps.supported-versions-matrix.outputs.lowest }}
      highest-version: ${{ steps.supported-versions-matrix.outputs.highest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect
        id: supported-versions-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1

  detect-tools:
    name: "Tools"
    runs-on: ubuntu-latest
    outputs:
      phpunit: ${{ steps.check_phpunit.outputs.files_exists }}
      infection: ${{ steps.check_infection.outputs.files_exists }}
      php-cs-fixer: ${{ steps.check_php-cs-fixer.outputs.files_exists }}
      psalm: ${{ steps.check_psalm.outputs.files_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHPUnit
        id: check_phpunit
        uses: andstor/file-existence-action@v1
        with:
          files: "phpunit.xml"

      - name: Infection
        id: check_infection
        uses: andstor/file-existence-action@v1
        with:
          files: "infection.json"

      - name: PHP-CS-Fixer
        id: check_php-cs-fixer
        uses: andstor/file-existence-action@v1
        with:
          files: ".php-cs-fixer.dist.php"

      - name: Psalm
        id: check_psalm
        uses: andstor/file-existence-action@v1
        with:
          files: "psalm.xml"