name: "CI detector"

on:
  workflow_call:
    outputs:
      php-supported-versions:
        value: ${{ jobs.detect-php-versions.outputs.versions }}
      php-lowest-version:
        value: ${{ jobs.detect-php-versions.outputs.lowest-version }}
      php-highest-version:
        value: ${{ jobs.detect-php-versions.outputs.highest-version }}
      phpunit:
        value: ${{ jobs.detect-phpunit.outputs.files_exists }}
      infection:
        value: ${{ jobs.detect-infection.outputs.files_exists }}
      php-cs-fixer:
        value: ${{ jobs.detect-php-cs-fixer.outputs.files_exists }}

jobs:
  detect-php-versions:
    name: "Detect PHP versions from composer.json"
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.supported-versions-matrix.outputs.version }}
      lowest-version: ${{ steps.supported-versions-matrix.outputs.lowest }}
      highest-version: ${{ steps.supported-versions-matrix.outputs.highest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect
        id: supported-versions-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1

  detect-phpunit:
    name: "Detect PHPUnit exists"
    runs-on: ubuntu-latest
    outputs:
      files_exists: ${{ steps.check_files.outputs.files_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "phpunit.xml"

  detect-infection:
    name: "Detect PHPUnit exists"
    runs-on: ubuntu-latest
    outputs:
      files_exists: ${{ steps.check_files.outputs.files_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "infection.json"

  detect-php-cs-fixer:
    name: "Detect PHPUnit exists"
    runs-on: ubuntu-latest
    outputs:
      files_exists: ${{ steps.check_files.outputs.files_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".php-cs-fixer.dist.php"