name: "Coding Standards PHP"

on:
  workflow_call:
    inputs:
      php-versions:
        default: >-
          ["8.0"]
        required: false
        type: string
      composer-dependencies:
        default: >-
          ["highest"]
        required: false
        type: string
      composer-options:
        default: "--no-progress --no-interaction --no-ansi"
        required: false
        type: string
      timeout-minutes:
        default: 30
        required: false
        type: number
      auto-commit:
        default: ""
        required: false
        type: string
    secrets:
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true

jobs:
  coding-standards:
    name: PHP ${{matrix.php-version}} with ${{matrix.composer-dependency}} dependencies
    runs-on: ${{matrix.operating-system}}
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        composer-dependency: ${{fromJson(inputs.composer-dependencies)}}
        operating-system:
          - "ubuntu-latest"
    timeout-minutes: ${{inputs.timeout-minutes}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{secrets.PACKAGIST_USER}} ${{secrets.PACKAGIST_TOKEN}}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{matrix.composer-dependency}}
          composer-options: ${{inputs.composer-options}}

      - name: Run friendsofphp/php-cs-fixer (dry-run)
        if: inputs.auto-commit == ''
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection $(git diff --name-only --diff-filter=ACMRTUXB "${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}}" | grep  -E "(.php$)")


      - name: Run friendsofphp/php-cs-fixer
        if: inputs.auto-commit != ''
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --using-cache=no --path-mode=intersection $(git diff --name-only --diff-filter=ACMRTUXB "${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}}" | grep  -E "(.php$)")

      - name: Auto Commit
        if: inputs.auto-commit != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fixed code-style