name: "Detect PHP versions from composer.json"

on:
  workflow_call:

jobs:
  detect-php-versions:
    name: "Detect PHP versions from composer.json"
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.supported-versions-matrix.outputs.version }}
      lowest-version: ${{ steps.supported-versions-matrix.outputs.lowest }}
      highest-version: ${{ steps.supported-versions-matrix.outputs.highest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect
        id: supported-versions-matrix
        uses: hschapitz/github-action-composer-php-versions-in-range@main