name: "Deploy to AWS EB"

on:
  workflow_call:
    inputs:
      php-versions:
        default: >-
          ['8.0']
        required: false
        type: string
    secrets:
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true
      AWS_KEY:
        required: true
      AWS_SECRET:
        required: true
      AWS_APPLICATION_NAME:
        required: true
      AWS_ENVIRONMENT_NAME:
        required: true
      AWS_REGION:
        required: true

jobs:
  deployment:
    name: PHP ${{matrix.php-version}} with locked dependencies
    runs-on: ${{matrix.operating-system}}
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{secrets.PACKAGIST_USER}} ${{secrets.PACKAGIST_TOKEN}}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"
          composer-options: "--no-progress --no-interaction --no-ansi"

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip