name: "Mutation tests with Infection"

on:
  workflow_call:
    inputs:
      php-versions:
        default: >-
          ['8.0']
        required: false
        type: string
      composer-dependencies:
        default: >-
          ['highest']
        required: false
        type: string
      composer-options:
        default: "--no-progress --no-interaction --no-ansi"
        required: false
        type: string
      min-msi:
        default: 100
        required: false
        type: number
      min-covered-msi:
        default: 100
        required: false
        type: number
      database:
        default: ''
        required: false
        type: string
      database-populate-command:
        default: 'php tests/createDatabase.php'
        required: false
        type: string
      database-version:
        default: 'latest'
        required: false
        type: string
      database-name:
        default: 'database'
        required: false
        type: string
      timeout-minutes:
        default: 30
        required: false
        type: number
    secrets:
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true

jobs:
  infection:
    name: PHP ${{matrix.php-version}} with ${{matrix.composer-dependency}} dependencies
    runs-on: ${{matrix.operating-system}}
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        composer-dependency: ${{fromJson(inputs.composer-dependencies)}}
        operating-system:
          - "ubuntu-latest"
    timeout-minutes: ${{inputs.timeout-minutes}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{secrets.PACKAGIST_USER}} ${{secrets.PACKAGIST_TOKEN}}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{matrix.composer-dependency}}
          composer-options: ${{inputs.composer-options}}

      - name: Stop default MySQL database
        if: inputs.database != ''
        run: sudo service mysql stop

      - name: Setup database MariaDB
        if: inputs.database == 'mariadb'
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: ${{inputs.database-version}}
          mysql database: ${{inputs.database-name}}
          mysql root password: ''

      - name: Wait for database
        if: inputs.database == 'mariadb'
        run: |
          while ! `mysqladmin ping -h 127.0.0.1 --silent`; do printf 'Waiting for database...\n'; sleep 1; done;
          mysql -h 127.0.0.1 -uroot -e 'SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,"ONLY_FULL_GROUP_BY",""))'

      - name: Populate database
        if: inputs.database != ''
        run: ${{inputs.database-populate-command}}

      - name: Test with infection/infection
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection --min-msi=${{inputs.min-msi}} --min-covered-msi=${{inputs.min-covered-msi}} --threads=4 --git-diff-lines --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered