name: "Mutation tests with Infection"

on:
  workflow_call:
    inputs:
      php-versions:
        default: >-
          ['8.0']
        required: false
        type: string
      composer-dependencies:
        default: >-
          ['highest']
        required: false
        type: string
      composer-options:
        default: "--no-progress --no-interaction --no-ansi"
        required: false
        type: string
      min-msi:
        default: 100
        required: false
        type: number
      min-covered-msi:
        default: 100
        required: false
        type: number
    secrets:
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true

jobs:
  infection:
    name: PHP ${{matrix.php-version}} with ${{matrix.composer-dependency}} dependencies
    runs-on: ${{matrix.operating-system}}
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        composer-dependency: ${{fromJson(inputs.composer-dependencies)}}
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{secrets.PACKAGIST_USER}} ${{secrets.PACKAGIST_TOKEN}}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{matrix.composer-dependency}}
          composer-options: ${{inputs.composer-options}}

      - name: Test with infection/infection
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection --min-msi=${{inputs.min-msi}} --min-covered-msi=${{inputs.min-covered-msi}} --threads=4 --git-diff-lines --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered