name: "Refactoring PHP with Rector"

on:
  workflow_call:
    inputs:
      php-versions:
        default: '8.0'
        required: false
        type: string
      composer-install:
        default: 'update'
        required: false
        type: string
    secrets:
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true

jobs:
  rector:
    name: PHP ${{ matrix.php-version }}
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{ secrets.PACKAGIST_USER }} ${{ secrets.PACKAGIST_TOKEN }}

      - name: Install dependecies
        run: composer ${{inputs.composer-install}} --no-progress --no-interaction --no-ansi

      - name: Refactoring with rector
        run: vendor/bin/rector process --dry-run $(git diff --name-only --diff-filter=ACMRTUXB "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}" | grep  -E "(.php$)")