name: "Unit tests with PHPUnit"

on:
  workflow_call:
    inputs:
      php-versions:
        default: '8.0'
        required: false
        type: string
      composer-install:
        default: 'update'
        required: false
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true

jobs:
  phpunit:
    name: PHP ${{ matrix.php-version }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{ secrets.PACKAGIST_USER }} ${{ secrets.PACKAGIST_TOKEN }}

      - name: Install dependecies
        run: composer ${{inputs.composer-install}} --no-progress --no-interaction --no-ansi

      - name: Test
        run: vendor/bin/phpunit

      - name: Send code coverage report to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}