name: "Unit tests with PHPUnit"

on:
  workflow_call:
    inputs:
      php-versions:
        default: >-
          ['8.0']
        required: false
        type: string
      composer-dependencies:
        default: >-
          ['highest']
        required: false
        type: string
      composer-options:
        default: "--no-progress --no-interaction --no-ansi"
        required: false
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      PACKAGIST_USER:
        required: true
      PACKAGIST_TOKEN:
        required: true

jobs:
  phpunit:
    name: PHP ${{matrix.php-version}} with ${{matrix.composer-dependency}} dependencies
    runs-on: ${{matrix.operating-system}}
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.php-versions)}}
        composer-dependency: ${{fromJson(inputs.composer-dependencies)}}
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}

      - name: Auth with private packagist
        run: composer config --auth http-basic.repo.packagist.com ${{secrets.PACKAGIST_USER}} ${{secrets.PACKAGIST_TOKEN}}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{matrix.composer-dependency}}
          composer-options: ${{inputs.composer-options}}

      - name: Test
        run: vendor/bin/phpunit

      - name: Send code coverage report to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}